"use client";

// Voice: a premium in page player that speaks a short demo out loud. The audio
// is generated by the Gemini Live TTS API on the server (see api/voice-demo);
// the client fetches it and plays it while a reactive waveform, driven by a
// Web Audio analyser, moves with the real voice. If the audio cannot load (for
// example the API key is not set yet) the waveform runs a synthetic animation
// so the player still feels alive. No text, no browser Siri voice.

import { useEffect, useRef, useState } from "react";

const BARS = 44;

export default function VoiceMemo() {
  const [playing, setPlaying] = useState(false);
  const [progress, setProgress] = useState(0);
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const ctxRef = useRef<AudioContext | null>(null);
  const analyserRef = useRef<AnalyserNode | null>(null);
  const rafRef = useRef(0);
  const barRefs = useRef<(HTMLSpanElement | null)[]>([]);

  useEffect(() => {
    const a = new Audio("/api/voice-demo");
    a.preload = "none";
    a.crossOrigin = "anonymous";
    a.onended = () => reset();
    audioRef.current = a;
    return () => {
      cancelAnimationFrame(rafRef.current);
      a.pause();
      ctxRef.current?.close().catch(() => {});
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const setBars = (fn: (i: number) => number) => {
    for (let i = 0; i < BARS; i++) {
      const el = barRefs.current[i];
      if (el) el.style.transform = `scaleY(${Math.max(0.06, fn(i))})`;
    }
  };

  const reset = () => {
    cancelAnimationFrame(rafRef.current);
    setPlaying(false);
    setProgress(0);
    setBars(() => 0.1);
    const a = audioRef.current;
    if (a) {
      a.pause();
      a.currentTime = 0;
    }
  };

  const buildGraph = () => {
    if (ctxRef.current || !audioRef.current) return;
    try {
      const Ctx =
        window.AudioContext ||
        (window as unknown as { webkitAudioContext: typeof AudioContext })
          .webkitAudioContext;
      const ctx = new Ctx();
      const src = ctx.createMediaElementSource(audioRef.current);
      const an = ctx.createAnalyser();
      an.fftSize = 128;
      an.smoothingTimeConstant = 0.72;
      src.connect(an);
      an.connect(ctx.destination);
      ctxRef.current = ctx;
      analyserRef.current = an;
    } catch {
      /* analyser unavailable, synthetic fallback still runs */
    }
  };

  const drawReactive = () => {
    const an = analyserRef.current;
    const a = audioRef.current;
    if (an) {
      const data = new Uint8Array(an.frequencyBinCount);
      an.getByteFrequencyData(data);
      setBars((i) => data[Math.floor((i / BARS) * data.length)] / 255);
    }
    if (a && a.duration) setProgress(a.currentTime / a.duration);
    rafRef.current = requestAnimationFrame(drawReactive);
  };

  const drawSynthetic = (start: number) => {
    const t = (performance.now() - start) / 1000;
    setBars(
      (i) =>
        (Math.sin(t * 7 + i * 0.5) * 0.5 + 0.5) *
        (0.35 + 0.65 * Math.sin((i / BARS) * Math.PI)),
    );
    setProgress(Math.min(1, t / 4.2));
    if (t < 4.2) {
      rafRef.current = requestAnimationFrame(() => drawSynthetic(start));
    } else {
      reset();
    }
  };

  const play = async () => {
    const a = audioRef.current!;
    buildGraph();
    await ctxRef.current?.resume().catch(() => {});
    try {
      a.currentTime = 0;
      await a.play();
      setPlaying(true);
      rafRef.current = requestAnimationFrame(drawReactive);
    } catch {
      setPlaying(true);
      rafRef.current = requestAnimationFrame(() => drawSynthetic(performance.now()));
    }
  };

  const toggle = () => (playing ? reset() : play());

  return (
    <div className="flex h-full w-full flex-col justify-center gap-6">
      <div className="flex items-center gap-5">
        <button
          type="button"
          onClick={toggle}
          aria-label={playing ? "Pause the voice demo" : "Play the voice demo"}
          className="flex h-16 w-16 shrink-0 items-center justify-center rounded-full bg-white text-black transition-transform duration-200 hover:scale-105"
        >
          {playing ? (
            <span className="flex gap-[5px]">
              <span className="block h-5 w-[3.5px] bg-current" />
              <span className="block h-5 w-[3.5px] bg-current" />
            </span>
          ) : (
            <span className="ml-1 block h-0 w-0 border-y-[9px] border-l-[15px] border-y-transparent border-l-current" />
          )}
        </button>

        <div className="flex h-20 flex-1 items-center gap-[3px]">
          {Array.from({ length: BARS }).map((_, i) => (
            <span
              key={i}
              ref={(el) => {
                barRefs.current[i] = el;
              }}
              className="h-full flex-1 origin-center rounded-full bg-white/70"
              style={{ transform: "scaleY(0.1)", transition: "transform .07s linear" }}
            />
          ))}
        </div>
      </div>

      <div className="h-px w-full bg-white/10">
        <div
          className="h-px bg-white/70"
          style={{ width: `${progress * 100}%`, transition: "width .1s linear" }}
        />
      </div>
    </div>
  );
}
